sonar.projectKey=QuickAi
sonar.projectName=QuickAi
sonar.projectVersion=1.0

sonar.language=js
sonar.sources=client,server

# Exclude heavy/unnecessary folders
sonar.exclusions=**/node_modules/**, **/dist/**, **/.vite-temp/**, **/build/**, **/.next/**, **/coverage/**, **/.git/**, **/logs/**
# JavaScript/TypeScript specific exclusions
sonar.javascript.exclusions=**/node_modules/**, **/dist/**
sonar.typescript.exclusions=**/node_modules/**, **/dist/**


# Increase bridge server timeout (default is 60s)
sonar.javascript.node.maxspace=4096

# Increase scanner web service timeout (default 300s = 5 min, set to 600s = 10 min)
sonar.ws.timeout=600

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# sonar.host.url=http://localhost:9000
# sonar.login=sqp_26750e39335ffa2afdf4fc4db78108885819f307
# sqp_71f42e5882f3264cca3b43881e7fdcd5bba5e53d

