sonar.projectKey=QuickAi
sonar.projectName=QuickAi
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=.

# Exclude heavy/unnecessary folders
sonar.exclusions=**/node_modules/**, **/dist/**, **/.vite-temp/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# sonar.host.url=http://localhost:9000
# sonar.login=sqp_26750e39335ffa2afdf4fc4db78108885819f307
# sqp_7c788e1996fac67acd9a34ee39af2b54f0dc302e

